modLoader = "javafml"
loaderVersion = "[1,)"
license = "${mod_license}"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_source}"
authors = "${mod_author}"
description = "${mod_description}"
logoFile = "logo.png"

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.5,1.21.1]"
ordering = "NONE"
side = "BOTH"