org.gradle.jvmargs=-Xmx4G

mod_id=no_caves
mod_version=0.5
mod_name=No Caves
mod_description=Disables Noise Caves, Density Function Caves, Generated Features, Carver Caves and Canyons based on the configuration, and maintains compatibility with other terrain modification mods and data packs as much as possible. Affects all biomes and all world generation presets by default.
mod_license=MIT
mod_author=Myitian
mod_source=https://github.com/Myitian/NoCaves

maven_group=net.myitian.no_caves

version_id=1.21.11
minecraft_version=1.21.11
supported_minecraft_version_fabric=1.21.11
# ResourceLocation was renamed to Identifier in MC 1.21.11
supported_minecraft_version_forge=1.21.11
supported_minecraft_version_neoforge=1.21.11
parchment_mappings=1.21.11:2025.12.20

enabled_platforms=fabric,forge,neoforge

fabric_loader_version=0.18.4
forge_version=1.21.11-61.0.3
neoforge_version=21.11.17-beta

mod_menu_version=17.0.0-beta.1
cloth_config_version=21.11.153

# required by other optional dependencies.
fabric_api_version=0.140.2+1.21.11