modLoader = "javafml"
loaderVersion = "[1,)"
license = "${mod_license}"

[[mixins]]
config = "no_caves-common.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_source}"
authors = "${mod_author}"
description = "${mod_description}"
logoFile = "assets/${mod_id}/logo.png"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.5,)"
ordering = "NONE"
side = "BOTH"